### ISSUE TITLE
new content: very simple logging as a debug helper

### ISSUE THREAD

**Issue by raffaelj** [zeraton-de/cockpit-docs#1]
I wrote a very simple helper to log variables for debugging and I updated my debug notes [here](https://github.com/raffaelj/cockpit-scripts/blob/master/debugging/debug_info.md).

Add this code snippet to the bootstrap of your addon or in `config/bootstrap.php`. Now you can call it from everywhere with `debug($variable);` and it writes a new line to `/storage/tmp/.log.txt`. I named it `.log` with a starting dot to let the `.htaccess` deny public access to it.

```php
// simple logging for debugging
function debug($message) {

    global $cockpit;

    if (!is_string($message) || !is_numeric($message))
        $message = json_encode($message);

    $time = date('Y-m-d H:i:s', time());

    $cockpit('fs')->write("#storage:tmp/.log.txt", "$time - $message\r\n", FILE_APPEND);

}
```

---

I have to finish two projects before I can have a deeper look at this repo. Soon...

**Comment by jankal** [comment]
@raffaelj Thank you very much! I'll have a look. I'm currently busy too, so there is no movement here.
